name: BaitersBurger Order Pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - 'develop'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests with Maven
        run: mvn -B test
        working-directory: ${{ github.workspace }}/baitersburger-orders

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application package with Maven
        run: mvn -B package -DskipTests
        working-directory: ${{ github.workspace }}/baitersburger-orders

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: baitersburger-orders-jar
          path: ${{ github.workspace }}/baitersburger-orders/target/*.jar

  docker-build:
    needs: [test, build]
    uses: ./.github/workflows/ecr.yml
    secrets: inherit

  deploy_ecs:
    needs: docker-build
    uses: ./.github/workflows/ecs.yml
    secrets: inherit
    with:
      image_uri: ${{ needs.docker-build.outputs.image_uri }}